"""Change orb id to passphrase (increase length to 64)

Revision ID: 0c8f0fccae7d
Revises: 555f452b2fac
Create Date: 2025-11-12 15:02:59.749480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c8f0fccae7d'
down_revision = '555f452b2fac'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orbs', 'id',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('papers', 'orb_id',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.drop_index('ix_papers_orb_id', table_name='papers')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_papers_orb_id', 'papers', ['orb_id'], unique=False)
    op.alter_column('papers', 'orb_id',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    op.alter_column('orbs', 'id',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    # ### end Alembic commands ###

